Fixing last mentions of Http and note for angular >4.3 users
ngx-translate/http-loader pull request #22
Opened 2017-08-07 08:57 UTC by Murazaki

2017-08-07 09:13 UTC, SamVerschueren requested changes
One small change

2017-08-07 09:13 UTC, SamVerschueren commented on README.md
> +**NB: if you're still on Angular >4.3, please use Http from @angular/http with http-loader@0.1.0.**
`Angular <4.3`

2017-08-07 10:32 UTC, SamVerschueren approved these changes

2017-08-07 10:45 UTC, merged

2017-08-07 10:46 UTC, ocombe commented
Thanks, I'm on holidays and my connection here is horrible, I cannot even check out the repo...

2017-08-08 07:25 UTC, Murazaki commented
Fix #20