Howto write a HashTranslateLoader
ngx-translate/http-loader pull request #39
Opened 2018-01-30 08:41 UTC by seveves

In issue #25 @mlegenhausen pointed out a solution that shows a very common use-case for a custom TranslateLoader implementation.
Maybe we can extend the readme to show this (and maybe other use-cases in the future)?

Kind regards :)

PS: my english is not the best, so feel free to improve it in any way

2018-03-15 07:49 UTC, tiaguinho requested changes
@seveves please, make this changes in your PR.

2018-03-15 07:49 UTC, tiaguinho commented on README.md
> +### HashTranslateLoader - Hashing translation files with angular-cli, webpack and SystemJS
I think you can remove the line  ```74``` and change the title to ```Angular CLI/Webpack TranslateLoader Example```

2018-03-15 07:49 UTC, tiaguinho commented on README.md
> +When your project cannot find `System` then adding this to your `typings.d.ts` file helps:
Cause ```System``` will not be available you need to add it to your custom ```typings.d.ts```

2018-03-15 07:49 UTC, tiaguinho commented on README.md
> +export class HashTranslateLoader implements TranslateLoader {
It's more accurate changing the class name to ```WebpackTranslateLoader```.

2018-03-15 07:49 UTC, tiaguinho commented on README.md
> +One disadvantage of this solution is that you have to rebuild your application when there are only changes inside your language files.
I think will be better changed to:

```The disadvantage of this solution is that you have to rebuild the application everytime your translate files has changes.```

2018-03-15 07:49 UTC, tiaguinho commented on README.md
> +Allow caching of translation files by the browser could help to speed up the initial load of your app but with the default setup your translation files could miss the latest changes because the cache
Drop this line.

2018-03-15 07:49 UTC, tiaguinho commented on README.md
> +When using the angular-cli (uses webpack under the hood) you can write your own `TranslateLoader` that always loads the latest translation file available during your application build.
```If you are using Angular CLI.....```

2018-03-16 11:14 UTC, seveves commented
@tiaguinho thank you for your review. I've updated the file to your suggestions.

2018-03-16 11:44 UTC, tiaguinho approved these changes

2018-03-16 13:36 UTC, merged

2018-03-16 13:36 UTC, ocombe commented
Thanks!